
# Project information
site_name: Material MKDocs template
site_url:  https://gagocarrilloedgar.github.io/mkdocs_template/
site_author: Edgar Gago Carrillo
site_description: >-
  This is a custom setup based on mkdocs.org and MKDocs Material
  that contains the basic project documentation config, including, README, 
  code of conduct and license

# Copyright
copyright: Copyright &copy; 2021 Edgar Gago Carrillo

# Page tree
nav:
  - Home: index.md
  - Examples: examples.md
  - Source code examples from JSDocs: source.md
  - Code of conduct: code_of_conduct.md
  - License: license.md


# Repository
repo_name: gagocarrilloedgar/mkdocs_template
repo_url: https://github.com/gagocarrilloedgar/mkdocs_template
edit_uri: ""

theme:
  name: material
  logo: assets/logo.png
  favicon: img/favicon.ico
  homepage: https://github.com/gagocarrilloedgar/mkdocs_template
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
  palette:
    - scheme: slate 
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to ligth mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
    
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  
# Plugins
plugins:
  - search
  - git-revision-date

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gagocarrilloedgar
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/edgargc9
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_youedgar
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/edgargagocarrillo/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/edgar.gago
    - icon: fontawesome/solid/paper-plane
      link: mailto:edgargc.upc@gmail.com